##################
#                #
#  Stay in tmux  #
#                #
##################
set-window-option -g remain-on-exit on
set-option -g destroy-unattached off

##################
#                #
#  vi copy-mode  #
#                #
##################
set-window-option -g mode-keys vi
# Setup 'v' to begin selection
bind-key -T copy-mode-vi v send-keys -X begin-selection
# Setup 'y' to yank (copy)
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# Update the default binding of 'Enter' to use copy-selection-and-cancel
#unbind-key -T copy-mode-vi Enter
# bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

################
#              #
#  Appearance  #
#              #
################
# Status bar styles
set -g status-right '#h %H:%M %Y-%m-%d %a'
set -g status-right-length 100
set-option -g status-position top
# Message styles
set-option -g display-time 1500
# Window styles
set -g window-status-style fg=default,bg=default
set -g window-status-bell-style fg=colour0,bg=colour1
set -g window-status-current-style fg=colour0,bg=colour7
set -g window-status-activity-style fg=colour0,bg=colour3
# Pane styles
set -g pane-border-status top
set -g pane-border-format '#[fg=colour2]###{pane_index}#{=/-36/...:pane_current_path}:#[fg=colour15]#{pane_current_command}'

###############
#             #
#  Usability  #
#             #
###############
# Enable mouse
set-option -g mouse on
# Quick reload configs
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded."
# Enable window bells
set-window-option -g monitor-activity on
set-window-option -g visual-bell both
set-window-option -g bell-action other
