##################
#                #
#  Stay in tmux  #
#                #
##################
set-window-option -g remain-on-exit on
set-option -g destroy-unattached off


##################
#                #
#  vi copy-mode  #
#                #
##################
set-window-option -g mode-keys vi
# Setup 'v' to begin selection
bind-key -T copy-mode-vi v send-keys -X begin-selection
# Setup 'y' to yank (copy)
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# Update the default binding of 'Enter' to use copy-selection-and-cancel
#unbind-key -T copy-mode-vi Enter
# bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel


################
#              #
#  Appearance  #
#              #
################
# ==== True color ====
# set -g default-terminal "tmux-256color"
# set-option -ga terminal-overrides ",${TERM}:Tc"
# ==== Status bar styles ====
set-option -g status-position top
set -g status-style bg=colour65
# Status left
set -g status-left '#[bg=colour115,fg=colour236] [#S|#{server_sessions}] '
# Status right
set -g status-right '#[fg=colour236,bg=colour115] #h %H:%M %Y-%m-%d %a '
set -g status-right-length 100
# Window status
set -g window-status-format ' #I:#W#F '
set -g window-status-current-format ' #I:#W#F '
set -g window-status-separator ''
set -g window-status-style fg=colour159,bg=colour65
set -g window-status-bell-style fg=colour159,bg=colour202
set -g window-status-current-style fg=colour159,bg=colour236
set -g window-status-activity-style fg=colour236,blink,bg=colour221
# ==== Message styles ====
set -g display-time 1000
set -g message-style fg=colour236,bg=colour159
# ==== Window styles ====
set -g window-style bg=colour236
# ==== Pane styles ====
set -g pane-border-status top
set -g pane-border-format '#[fg=colour115] [#{pane_index}]#{=/-36/...:pane_current_path}:#[fg=colour159]#{pane_current_command} '
set -g pane-border-style none,fg=colour65
set -g pane-active-border-style none,fg=colour115


###############
#             #
#  Usability  #
#             #
###############
# Enable mouse
set-option -g mouse on
# Quick reload configs
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded."
# Enable window bells
set-window-option -g monitor-activity on
set-window-option -g visual-bell both
set-window-option -g bell-action other
# Count from 1 for better shortcut experience
set -g base-index 1
setw -g pane-base-index 1
